## Numpy codes for practicing functions

#### Why to use Numpy

- NumPy is a Python library used for working with arrays.
- NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

#### Import numpy and make a numpy array

In [1]:
import numpy as np

In [3]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

print(arr,' ', arr.dtype)

[ 1  2  3  4  5  6  7  8  9 10]   int64


#### Define data type of array

In [5]:
arr2 = np.array([1, 2, 3, 4, 5], dtype = 'S')
print(arr2,' ', arr2.dtype)

[b'1' b'2' b'3' b'4' b'5']   |S1


#### Copying and viewing numpy arrays

In [6]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
x = arr.copy()
arr[0] = 42
print(arr)
print(x)

[42  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]


In [8]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
x = arr.view()
arr[0] = 42
print(arr)
print(x)

x[0] = 78
print(arr)
print(x)

[42  2  3  4  5  6  7  8  9 10]
[42  2  3  4  5  6  7  8  9 10]
[78  2  3  4  5  6  7  8  9 10]
[78  2  3  4  5  6  7  8  9 10]


In [9]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[ 1  2  3  4  5  6  7  8  9 10]


#### Shape and reshape arrays

In [10]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(arr.shape)

(10,)


In [11]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [14]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr,'\n')

newarr = arr.reshape(2, 3, 2)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] 

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [15]:
arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)


(0,) 1
(1,) 2
(2,) 3


In [16]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8
